#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH=${DIR}
export CUSTOM_PI_OS_PATH="$DIR/../CustomPiOS/src"
export PATH=$PATH:$CUSTOM_PI_OS_PATH

if [ "${GET_IMAGE:-}" ]; then
    DEST="$DIR/.." "$DIR/download_raspbian"
fi

rsync -av --delete \
    "$DIR/../../pyStranger" \
    "$DIR/modules/strangerpi/filesystem/home/pi"

"$CUSTOM_PI_OS_PATH/build_custom_os" "$@"
