#!/usr/bin/env bash
set -Eeuo pipefail

echo "Downloading latest Raspbian image"

version="raspios_lite_armhf"


if ! CURRENT_RASPBIAN=$(
    curl "https://downloads.raspberrypi.org/$version/images/" \
    | grep raspios | tail -n 1 | awk -F "href=\"" '{print $2}' | awk -F "/" '{print $1}'
); then
    echo "error getting date"
    exit 1
fi
echo "$CURRENT_RASPBIAN"


CURRENT_RASPBIAN_FILE=$(
    curl "https://downloads.raspberrypi.org/$version/images/$CURRENT_RASPBIAN/" \
    | grep .img.xz | head -n 1 | awk -F "href=\"" '{print $2}' | awk -F "\">" '{print $1}'
)

echo "$CURRENT_RASPBIAN_FILE"

mkdir -p "$DEST/src/image"
curl -L -o "$DEST/src/image/$CURRENT_RASPBIAN_FILE" \
"https://downloads.raspberrypi.org/$version/images/$CURRENT_RASPBIAN/$CURRENT_RASPBIAN_FILE"
