name: StrangerFamily build

on: [push, pull_request]


jobs:
  build_custom_pi_os:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: { submodules: true }

    - name: Cache Raspbian image
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: StrangerPi/src/image
        key: ${{ runner.os }}-raspbian-image

    - name: Download Raspbian Image
      run: |
        cd StrangerPi/src/image
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'

    - name: Cache chroot apt
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: StrangerPi/src/workspace/aptcache/
        key: ${{ runner.os }}-custompios-apt

    - run: |
        sudo apt update
        sudo apt install qemu-user-static

    - name: Build CustomPiOS
      run: sudo StrangerPi/src/build_dist

    - name: Upload Raspberry pi image
      uses: actions/upload-artifact@v2
      with:
        name: raspberry_pi_images
        path: StrangerPi/src/workspace/*.img


  build_arduino_firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO
      run: |
        cd arduinoSerialPixel
        pio run -e nanoatmega328new -e nanoatmega328

    - name: Upload Arduino firmware
      uses: actions/upload-artifact@v2
      with:
        name: arduino_firmwares
        path: |
          arduinoSerialPixel/.pio/build/nanoatmega328/firmware.*
          arduinoSerialPixel/.pio/build/nanoatmega328new/firmware.*
